# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: nicetauren
google_analytics: dbyll
title: Nicetauren

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nicetauren's Blog

description: Nicetauren's Blog 
author:
  name: nicetauren
  email: woduf0628@pusan.ac.kr
  github: nicetauren
  linkedin: jaeyeol-park-381170270
  bio: Hello, World!
  email_md5: f1fe404d868060af8b3131c1e48e84d3

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
